//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHANG.Conttext
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string caterogyId { get; set; }
        public string shortdes { get; set; }
        public string fulldesciption { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> pricediscount { get; set; }
        public Nullable<int> typeid { get; set; }
        public string slug { get; set; }
        public Nullable<int> brandld { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> showonhomepage { get; set; }
        public Nullable<int> displayorder { get; set; }
        public Nullable<System.DateTime> createdonutc { get; set; }
        public Nullable<System.DateTime> updatedonutc { get; set; }
    }
}
