//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHANG.contex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Xml.Linq;

    public partial class Brand
    {
        public int id { get; set; }
        [Display(Name = "Tên thương hiệu")]
        public string name { get; set; }
        [Display(Name = "Ảnh thương Hiệu")]
        public string avatar { get; set; }
        [Display(Name = "Loại")]
        public string slug { get; set; }
        [Display(Name = "hiện lên trang chủ")]
        public Nullable<bool> showonhomepage { get; set; }
        [Display(Name = "thứ tự trình bày")]
        public Nullable<int> displayorder { get; set; }
        public Nullable<System.DateTime> cretedonutc { get; set; }
        public Nullable<System.DateTime> updateonutc { get; set; }
        public Nullable<bool> deleted { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpLoat { get; set; }
    }
}
