//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHANG.contex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Oder
    {
        public int id { get; set; }
        [Display(Name = "Tên Đơn Hàng")]
        public string name { get; set; }
        [Display(Name = "MÃ Người dùng")]
        public Nullable<int> uerId { get; set; }
        [Display(Name = "tình trạng")]
        public Nullable<int> Status { get; set; }
        [Display(Name = "Ngày Mua Hàng")]
        public Nullable<System.DateTime> CreateOnUtc { get; set; }
    }
}
